### ISSUE TITLE
Fail on brew install buf

### ISSUE THREAD

**Issue by andymo-sportsbet** [bufbuild/homebrew-buf#4]
go: github.com/gofrs/flock@v0.8.1: Get “https://proxy.golang.org/github.com/gofrs/flock/@v/v0.8.1.mod”: x509: certificate signed by unknown authority

What do we need to do on our side?

**Comment by amckinney** [comment]
I can't reproduce this on my end - I was able to successfully run `brew install buf` and received the latest `v1.0.0-rc7` version.

I'm not sure why you're seeing this error - can you provide more context w.r.t your current setup?

**Comment by bufdev** [comment]
This appears to be a (likely transient) issue with your local development machine, not an issue with this formula, let us know if you have other issues.
