### ISSUE TITLE
brew install buf fail

### ISSUE THREAD

**Issue by dmskys** [bufbuild/homebrew-buf#5]
go: github.com/gofrs/flock@v0.8.1: Get "https://proxy.golang.org/github.com/gofrs/flock/@v/v0.8.1.mod": dial tcp 172.217.160.113:443: i/o timeout

**Comment by bufdev** [comment]
This isn't a buf issue, this is an issue with your local development environment.

**Comment by wenmingtang** [comment]
`export https_proxy=http://127.0.0.1:1087`
