### ISSUE TITLE
Compilation failure on fresh Solus install

### ISSUE THREAD

**Issue by stabai** [bufbuild/homebrew-buf#7]
I just did a fresh install of the Solus Linux distro with Budgie desktop environment. After installing homebrew, I tried to reinstall Buf and got this error:

`$ brew install bufbuild/buf/buf`

```
==> sh make/buf/scripts/brew.sh .build/brew
Last 15 lines from /home/stabai/.cache/Homebrew/Logs/buf/01.sh:
2022-03-14 20:18:33 +0000

sh
make/buf/scripts/brew.sh
.build/brew

go build -ldflags "-s -w" -trimpath -o ".build/brew/bin/buf" "cmd/buf/main.go"
# runtime/cgo
_cgo_export.c:3:20: fatal error: stdlib.h: No such file or directory
compilation terminated.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/bufbuild/homebrew-buf/issues
```

This looked like an issue with the go compiler to me, so I ensured that go is installed and rebooted the machine, but the problem still persists.

Homebrew version info:
```
Homebrew 3.4.1
Homebrew/homebrew-core (git revision 7c6c22befcb; last commit 2022-03-14)
```

Linux64 version info:
```
linux64 from util-linux 2.37.4
```

**Comment by stabai** [comment]
I was able to resolve this by installing Solus' equivalent of the `build-essentials` package:
`sudo eopkg install -c system.devel`

I guess I was supposed to know to do that somehow, but more of a Solus issue than a Buf issue.

**Comment by timostamm** [comment]
Hey Shawn, thanks for the report. Yes, it looks like solus doesn't come with any [compiler tooling](https://getsol.us/articles/package-management/basics/en/#base-development-tools). We publish a few distribution-specific packages, but not for `eopkg`, and right now, we do rely on a few developer prerequisites.

Closing this, but if you encounter a bug, please feel free to re-open.
